### ISSUE TITLE
Support for cancellation token

### ISSUE THREAD

**Issue by marcoregueira** [4egod/MJPEG#1]
Hi 

I've found this package really useful and worked well for my purposes, but I found it was lacking a way to stop gracefully.

I've added support for cancellation tokens, to avoid the tool from hanging for too long when connecting to unresponsive endpoints. It can also be used to limit the time you're capturing images, or even limit capturing to only one frame if you call cancel on the first FrameReceived event.

I'm sending you a pull request. I hope you find it useful. It would be really useful for me to have this functionality in the nuget package.

**Comment by i4egod** [comment]
Completed.
#2
